# Based on BachoSeven/dotfiles

# use_nerdfont = true
flip_status_indicators = true

##################
# Track manipulation
##################
[keybindings]
"D" = "delete"

######################################
# Sorting
######################################
"t" = "sort added d"
"T" = "sort title a"

######################################
# Other
######################################
"Q" = "quit"
"Z" = "quit"

# Gruvbox dark [ originally based on base16 by Dawid Kurek (dawikur@gmail.com) ]
[theme]
background = "#1d2021"
primary = "#a89984"
secondary = "#928374"
title = "#8ec07c"
playing = "#689d6a"
playing_selected = "#ebdbb2"
playing_bg = "#383838"
highlight = "#d5c4a1"
highlight_bg = "#484848"
error = "#fbf1c7"
error_bg = "#cc241d"
statusbar = "#98971a"
statusbar_progress = "#458588"
statusbar_bg = "#1d2021"
cmdline = "#d5c4a1"
cmdline_bg = "#383838"
search_match = "#fabd2f"
