unbind C-b

set-option -g prefix C-a
bind-key C-a send-prefix

# set -g prefix C-a
set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g status on
set -g status-interval 5
set -g status-left " #S | "
set -g status-right "%Y-%m-%d %H:%M"
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
set -g escape-time 0
set -g focus-events on

bind r source-file ~/tmux/tmux.conf \; display-message "Config reloaded"

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
